### ISSUE TITLE
Validate monitoring data

### ISSUE THREAD

**Issue by princiya** [zalando/zalando.github.io#111]
## Validate the monitoring data

We have a basic monitoring infrastructure [setup](https://github.com/zalando/roadblock). We now have to validate this and ensure we are getting and storing the data with appropriate foreign key mappings, right values etc.

### Tasks

- [x] Refactor the code
- [x] Debug the store / write calls
- [x] Check table associations
- [x] Clean up associations in the schema

### Expected delivery

We have very clean data which can be visualised well.
