### ISSUE TITLE
Restructure open source strategy document

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#112]
## Task Headline

Based on feedback during last weeks meeting, write proposal for restructuring the structure of the strategy document. 

### Tasks
This is the concreate tasks to complete before the task is marked as done

- [x] Include structure based on DF OKRs
- [x] Structure our objectives under DF OKRs 
- [x] Add operational tasks as examples of what we will do
- [x] Order team KPI's under operational tasks
- [ ] Order objectives in matrix as per suggestion during last weeks meeting

### Expected delivery

A new google drive document with a new strategy structure based on feedback. 

## Stakeholders
Who do we need to colloborate with to make this happen? - add the department to get in touch with

- [ ] HH
