### ISSUE TITLE
Opensource Roadblock

### ISSUE THREAD

**Issue by princiya** [zalando/zalando.github.io#114]
## Opensource Roadblock

Move Roadblock repository from private to public into zalando-incubator.

### Tasks

- [x] Documentation
- [x] Move repo from zalando to zalando-incubator
- [x] Docs / templates
- [x] Security - remove tokens from git history (https://help.github.com/articles/removing-sensitive-data-from-a-repository/)

### Expected delivery

Roadblock is now opensource and is available to everyone.

## Stakeholders

- [ ] Inform the guild

## How do we measure the task was completed

- [ ] Get feedback from the guild
