### ISSUE TITLE
Automate Github Api Tooling - TrafficLight

### ISSUE THREAD

**Issue by princiya** [zalando/zalando.github.io#116]
## Automate Github Api Tooling

Build a Node.js CLI tool to automate creation of new repository and migration of existing repository. This is part of the Github organisation restructuring.

### Tasks

**New repository**

- [x] Setup repo + `team-<projectname>`
- [x] Organise team under 'projects' team
- [x] Invite owner + members to team
    - setup repository permissions according to compliance
        - 2 person review
      - protected master branch
      - mandatory files, readme, security, etc 
- [x] Copy mandatory files from new-project to speed up project creation 
- [x] Create an issue on the tracker with tasks for initial setup

**Migrate repository**

- [x] Get teams with admin/write permissions which are not `team-<projectname>`
      - get team members of these teams
      - add new team called `team-<projectname>` with write permissions
      - add teams memembers to `team-<projectname>`
- [x] Remove old team from repo --> move to legacy parent team
- [x] Check for community profile issues ~~and report as an issue on the repository~~

### Expected delivery

Launch **TrafficLight** :)

## Stakeholders

- [ ] Guild

**Comment by perploug** [comment]
Added a task for automatically copying project files from new-project to speed up creating of new projects
