### ISSUE TITLE
Deprecate Catwatch

### ISSUE THREAD

**Issue by princiya** [zalando/zalando.github.io#121]
## Deprecate Catwatch

We now have Roadblock. To cut down AWS costs, we can now deprecate Catwatch.

### Tasks

- [ ] Announce deprecation
- [x] Check who is using Catwatch
- [ ] Create a `cron job` to get data 
- [x] Output the data into json file
- [x] add alternative solution #171 

### Expected delivery

- Roadblock replaces Catwatch.
- The OST website uses data from Roadblock.

## Stakeholders

- [ ] Guild

**Comment by perploug** [comment]
The jobs.zalando.com website uses catwatch:
- https://github.bus.zalan.do/musketeers/global-jobsite-static-gen 
- https://jobs.zalando.com/tech/ 

There might be zmon tasks which checks catwatch:
- https://github.bus.zalan.do/mniebes/zmon-checks/blob/3007a9b882d2a63a8830df57eb593b6c14221025/all-checks/zmon-check-3619.yaml

**Comment by perploug** [comment]
- For now we will manually push new json files to opensource.z.com
- Data already generated by roadblock
- Need to rewrite the js on opensource.z.com

**Comment by perploug** [comment]
Js has been reviewed - PR has been opened #189
