### ISSUE TITLE
Maintainer Training

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#128]
## Task Headline

In order to create a high quality experience for contributors to Zalando open source projects. 
We will design a maintainer training program which helps our project maintainers to create and nurture 
welcoming and friendly open source projects. 

### Tasks
- [x] Write narrative
- [x] Define overall structure of the material
  - [x] Content for Introduction course
  - [ ] Content for Mentorship and coaching part
  - [ ] Content for Advocacy and stewardship part
- [x] Decide on the format of the training, online, classroom, other?
- [x] Decide who this is offered? tech, onboarding, other?
- [ ] Promotion
- [ ] Include in Incubator graduation process

### Expected delivery

Training materials for maintainers, offered through the tech academy to all zalando project maintainers

### Format
- Training is planned be delivered in 3 parts:
  - Open Source Maintainance Basics, Maintainer Role, Compliance and the incubator process
  - Project advocacy and stewardship
  - Project mentorship and coaching

The training will be structured as a set of slides for all 3 courses, the introduction course will be designed to be available as an online course, but initial offered as a classroom course for quick
initial feedback. The 2 more advanced courses requires attendee interaction and is therefore 
structured as classroom training. 

Training is offered to current maintainers and new maintainers in the incubation process, new maintainers will therefore have 6 months to take the training as part of their project incubation.

## Stakeholders
Who do we need to align with to make this happen? - add the deparment to get in touch with

- [ ] Tech dep leads
- [ ] Tech academy

## How do we measure the task was completed
How do we measure impact 

  1. number of maintainers trained
  1. attendee feedback

**Comment by perploug** [comment]
Dublicate issue
