### ISSUE TITLE
Framework for project promotion

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#131]
## Task Headline

We need to create a framework for how projects, maintainers and Zalandos general open source efforts are promoted. 

Further refinement of this topic is required to establish what initiatives are required for promoting new and existing projects. 

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [x] Refine content plan
- [x] Decide on media channels, twitter, linkedIn, other?
- [ ] Internal channels - include project in guild meetings

### Expected delivery

Complete framework and tasklist for promoting new and existing projects

## Stakeholders
Who do we need to align with to make this happen? - add the deparment to get in touch with

- [ ] Corp comms
- [ ] Employer branding

## How do we measure the task was completed
How do we measure impact 

  1. Linkedin Elevate

Please review[ here ](https://docs.google.com/document/d/1jOV0Z60vHs2QhvWxupCcjiMVpQfMyuNxJ1p_RX7qCZI/edit)

**Comment by hpdang** [comment]
please review https://docs.google.com/document/d/1jOV0Z60vHs2QhvWxupCcjiMVpQfMyuNxJ1p_RX7qCZI/edit
