### ISSUE TITLE
Website Subsection Landing Page

### ISSUE THREAD

**Issue by baggerspion** [zalando/zalando.github.io#141]
## Task Headline

We should have consistently-styled landing pages for subsections of the website where we are aggregating content, e.g. blog, docs

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [x] Create general landing page template
- [x] Create special versions for blog, docs...
- [x] Styling using dress-code

### Expected delivery

- New landing page is build and designed for docs and blog
- Merged and deployed to website
