### ISSUE TITLE
Create blogpost on the launch of the open source report

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#159]
## Blogpost on the state of open source report

Corp comms have provide a template and guidance on writing a post on the tech blog, this post must be completed no later than monday so it can be reviewed and queued for publishing. This tasks depends on the report being complete ofcourse. (PR #158 and task #144)  

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [x] Headline and subheadline
- [x] Categories and tags
- [x] Put together 3/4 of a page of content with background, reasoning and outlook

### Expected delivery

Filed out template and a blog post ready for review monday.

## Stakeholders
Who do we need to align with to make this happen? - add the deparment to get in touch with

- [x] Corp comms (already briefed)

## How do we measure the task was completed
How do we measure impact 

  1. Traffic on the blog post
  1. Traffic on opensource.z from the blog and SoMe
  1. SoMe traffic (Measure activity on twitter and LinkedIn)
