### ISSUE TITLE
Travis CI Link checking

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#168]
## Task Headline

Automate link checking on pages published on the blog to ensure we do not have 404s on links and images. 

Travis CI can be used to do this - @therealpadams has a code snippet to do this task

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [ ] Setup Travis CI
- [ ] Configure automated link checking resulting in build failures
- [ ] Test on blog and non-blog content

### Expected delivery

Travis CI should blog builds with broken links and block PRs to get merged in if they result in broken links

**Comment by perploug** [comment]
This has been disabled for now, so this task is not fully completed, but would be a nice thing to have on the blog.
