### ISSUE TITLE
Replace catwatch on opensource.zalando.com

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#171]
## Task Headline

As we currently use Catwatch data ourselves, we must replace this use on the website with a solution which uses the roadblock json file output

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [x] Find hosting for json files
- [x] Look into how to deliver to websites
- [ ] Automation of file generation

### Expected delivery

A solution which our website and other websites can use to replace their dependency on catwatch

## Stakeholders
Who do we need to align with to make this happen? - add the deparment to get in touch with

- [ ] EB

**Comment by perploug** [comment]
No automation needed for now - we will rerun the export each month

PR> https://github.com/zalando/zalando.github.io/pull/189
