### ISSUE TITLE
Get sign-off on IP document

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#172]
## Task Headline

- Ensure the IP document is signed off by the relevant VP
- Coordinate with employment law dep on contract amendment 
- Coordinate with p&o on inclusion in onboarding and contract signing process
- Find out what the process is for existing employees
- Determine scope of contract, does this apply to other than devs in tech div. 
- Establish a process for adding projects to the whitelist: suggestion: manage in a ghe repo with Pull Requests from the employees, approved by OST and the relevant lead.

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [x] Add examples for each of the 3 clauses in the contract (#181 )
- [ ] Get sign-off
- [ ] Get approval from employment law
- [ ] Get p&o onboard
- [x] Inform Compliance on this new document and deprecate the old one. 
- [ ] Create hype (discuss with Corp comms)
- [ ] Discuss on open sourcing the template

## Expected output

  1. Contract amended
  1. Hype created
  1. Template open sourced

## Stakeholders
Who do we need to align with to make this happen? - add the deparment to get in touch with

- [ ] Legal
- [ ] Compliance
- [ ] M&E VP
- [ ] Employment law

**Comment by perploug** [comment]
Added examples to the document and converted it back into a markdown format document.

**Comment by perploug** [comment]
Added an example workflow for managing the project whitelist, could work with a PR-based review model on GHE
