### ISSUE TITLE
Update IP contract with examples and whitelist link

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#181]
## Examples and converted to markdown

Update the document with examples for each of the 3 clauses so it is clear what each clause means. 

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [x] Examples
- [x] Convert to markdown
- [x] Move the whitelist of projects to a seperate document
- [x] Workflow for whitelist proposal

### Expected delivery

Contract in markdown with a separate whitelist and examples

**Comment by perploug** [comment]
Agreement in markdown and with examples:

https://github.com/perploug/balanced-employee-ip-agreement/blob/master/Balanced_Employee_IP_Agreement.md

Proposed workflow and whitelisting format:
https://github.com/perploug/balanced-employee-ip-agreement/blob/master/project-ip-whitelist.md

**Comment by baggerspion** [comment]
We need to be careful with the examples in 2.iii:
- "You can't do this on work time" is kinda covered already
- "You cannot use your company laptop" is somewhat undesirable (the Z-issued laptop might be the only machine an engineer has)

**Comment by perploug** [comment]
@therealpadams - updated the document on drive with improved laptop wording and change of exemples

**Comment by baggerspion** [comment]
The above links need updating... I get 404s

**Comment by perploug** [comment]
Process was moved to google docs: 
https://docs.google.com/document/d/1EqRAYzsRY5rRYn3jNot8SzDUo7woarcLsCd8lB8xMsE/edit
