### ISSUE TITLE
Outline the review process

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#188]
## Task Headline

Figure out how the workflow for Open source reviews work

- How does people find the form?
- Where does the submitted form go?
- Who acts on the submitted form?
- What is a reasonable response time?
- How do we mark reviewed items as "done"
- How do we ensure that review items are not lost in the process?

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [x] Connect google form with github team discussions
- [x] Create issues for items in review?
- [x] Describe flow and timeframes for the review group
