### ISSUE TITLE
Create a standard announcement email template

### ISSUE THREAD

**Issue by hpdang** [zalando/zalando.github.io#236]
To raise awareness for new project

### Tasks
- [x] Look at some examples 
- [x] Create a simple text template 
- [x] Publish on opensouce.z.com

### Expected outcome 
 -  A sample email - published on opensource.z.com

**Comment by hpdang** [comment]
Please review https://docs.google.com/document/d/1HqmRhx0igyxtf-xolRgCuWnImEbrXh3nxFaK8dNAhFs/edit#

**Comment by baggerspion** [comment]
Excellent! The next step for this: we need to work out where to put such content in our website. But I certainly think this is good for inclusion into the website. Question: did you take the screenshots? Cannot include in the website if not.
