### ISSUE TITLE
Social Media Promotion for open source projects

### ISSUE THREAD

**Issue by hpdang** [zalando/zalando.github.io#237]
Help project to raise awareness via social media

### Tasks

- [x] Decide on which channels to use
- [x] Decide: can projects have their own SOME accounts?
- [x] Decide on the process for @ZalandoTech mentions
- [x] Sample messages

### Stakeholder
- [x] Employer branding

### Expected output
- Onepage on social media guidance for os projects

**Comment by hpdang** [comment]
Ready to review https://docs.google.com/document/d/1YIy-neQ_tkIZ_uZXf7_d31rKp8wNNQLHcW5H2KMpw64/edit#

**Comment by hpdang** [comment]
Fixed based on comment. Please review again https://docs.google.com/document/d/1YIy-neQ_tkIZ_uZXf7_d31rKp8wNNQLHcW5H2KMpw64/edit
