### ISSUE TITLE
Create a product intro sample blogpost

### ISSUE THREAD

**Issue by hpdang** [zalando/zalando.github.io#238]
Help project to raise awareness 

### Tasks
- [x] Look how other open source projects does this 
- [x] Write a blogpost template
- [x] Publish on opensouce.z.com

### Expected outcome 
 - One page document of structure template - published on opensource.z.com

**Comment by hpdang** [comment]
please review https://docs.google.com/document/d/1n7sP6CrI2Fyt2OvS-qMGHEp_6npdBnUGuYB3vkrkBWk/edit#
