### ISSUE TITLE
Guide how to organize a release event/party 

### ISSUE THREAD

**Issue by hpdang** [zalando/zalando.github.io#239]
To raise awareness for new project

### Tasks
- [x] Look how other open source projects does this
- [x] Get input from COMA
- [x] Write a one-pager on setting up release party
- [x] Publish on opensouce.z.com

### Stakeholders
- [x] Coma team

### Expected outcome 
 - One page document on arranging release party - published on opensource.z.com

**Comment by hpdang** [comment]
Ready to review 
https://docs.google.com/document/d/1zAasJN7zq87nlj43oKUD3QDcF2kSL_fG_5pEgHrn3TM/edit#heading=h.wejbi5fxiast

**Comment by perploug** [comment]
Read through the document, looks good, corrected a couple of things, removed the reference to eventyay. Added a suggestion for a point of follow-up and measurement of success.

**Comment by hpdang** [comment]
updated, please review https://docs.google.com/document/d/1zAasJN7zq87nlj43oKUD3QDcF2kSL_fG_5pEgHrn3TM/edit#heading=h.wejbi5fxiast
