### ISSUE TITLE
Launch pilot projects on the project promition framework

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#258]
## Task Headline

As the first part of the promotion framework is complete, we need to start actively using it with our open source projects. 

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [ ] find projects that would be suitable as pilot projects
- [ ] work out metrics for success
- [ ] collect feedback from projects

### Expected delivery

As the project is put into use, we gather feedback from the projects, the end result is a refined framework and increase contribution count on these projects. 

## Stakeholders
Who do we need to align with to make this happen? - add the deparment to get in touch with

- [ ] Department name

## How do we measure the task was completed
How do we measure impact 

  1.
  1.
  1.
