### ISSUE TITLE
Conduct Developer Survey 

### ISSUE THREAD

**Issue by hpdang** [zalando/zalando.github.io#260]
## Task Headline
To understand the workforce's value, human asset and identify potential InnerSource project

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [ ] Create a questionnaire in Google Form 
- [ ] Feedback from the team 
- [ ] Get approval to send out to all developers  
- [ ] Send out survey and monitor the result 

### Expected delivery
Survey report with graphs and learning outcome 

## Stakeholders
- [ ] VP 

## How do we measure the task was completed
How do we measure impact 
  1. No. of participants 
  2. No. of lead projects for InnerSource
  3. No. of outstanding developers being identified during the survey
