### ISSUE TITLE
Monthly OS newsletter

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#270]
## Task Headline

Create a monthly newsletter for internal distribution at Zalando.  Content for the newsletter is
aggregated items related to open source - ei. we will not produce editorial content, but simply send out a summary of the months activities in regards to open source.

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [ ] Identify Content Sources
- [ ] Decide on frequency and audience
- [ ] Add analytics
- [ ] Create a template - talk to COMA
- [ ] Decide on tooling - Mailchimp?

### Expected delivery

TBR

## Stakeholders
Who do we need to align with to make this happen? - add the deparment to get in touch with

- [ ] Corp comms
- [ ] COMA

## How do we measure the task was completed
How do we measure impact 

TBR
