### ISSUE TITLE
Conduct Adoption (Developer) Survey 

### ISSUE THREAD

**Issue by hpdang** [zalando/zalando.github.io#271]
## Task Headline
Conduct An Adoption Survey Across Zalando Tech. 

The purpose of this survey is to analyse the current open source usage across Zalando tech, to identify key players in the ecosystem and potential new contributors to Zalando Open Source projects, to raise awareness of engineers on current open source efforts at Zalando. 

Target: Zalando Tech 

### Tasks
- [ ] Create a narrative 
- [ ] Align with stakeholders
- [ ] Write survey questions
- [ ] Follow-up and promotion of survey
- [ ] Write a report 

### Expected deliveryThese are the concrete tasks to complete before the issue is marked as done:
Final report with learning outcomes. 

## Stakeholders
- [ ] COMA
- [ ] Tech Academy 

## How do we measure the task was completed
Impact is measured based on: 
- No. of participants 
- No. of unknown open source contributors 
- No. of valuable open source tools
