### ISSUE TITLE
Maintainer podcast

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#272]
## Task Headline

Create a podcast on open source and the maintainers of open source at Zalando to create awareness of the work done by Zalando engineering teams. 

During Q4 we will do 3 trial runs of the concept to test out on select audience to see if the concept works, we can deliver something of value and if it is worth the time required. 

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [ ] Identify topics and guests
- [ ] Identify test audience
- [ ] Design concept
- [ ] Investigate tools and equipment
- [ ] Feedback survey
- [ ] Update narrative

### Expected delivery

What is the concrete outcome of this work: 

## Stakeholders
Who do we need to align with to make this happen? - add the deparment to get in touch with

- [ ] Department name

## How do we measure the task was completed
How do we measure impact 

  1.
  1.
  1.
