### ISSUE TITLE
EOY Report on the state of open source

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#273]
## Task Headline

Based on the interim report published in June, we will design a EOY report on the state of Open source. The report should contain key figures, show progress from the last report and details on our company strategy for open source. 

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [ ] Write editorial content
- [ ] Gather updated numbers
- [ ] Sync with Stakeholders
- [ ] Launch and hypeplan

### Expected delivery

What is the concrete outcome of this work: 

In december we publish a page on opensource.z.com containing the EOY report. 

## Stakeholders
Who do we need to align with to make this happen? - add the deparment to get in touch with

- [ ] Corp Comms
- [ ] EB

## How do we measure the task was completed
How do we measure impact 

  1. Visitors on page
  1. Launch blogpost readers
