### ISSUE TITLE
Techhub Tour

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#274]
## Task Headline

We want to reach our customers and partners in the remote techhubs (portugal, ireland and finland).
The open source team will reach out to the techhubs and arrange a open source day with workshop content - content to be decided on - and depending and techhub feedback. 

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [ ] Budget approval
- [ ] Agree dates with sites
- [ ] Identify remote stakeholder
- [ ] Design feedback survey
- [ ] Assign sites and setup comms

### Expected delivery

What is the concrete outcome of this work: 

3 workshops delivered (1 at each techhub)

## Stakeholders
Who do we need to align with to make this happen? - add the deparment to get in touch with

- [ ] Techhubs
- [ ] COMA

## How do we measure the task was completed
How do we measure impact 

  1. Number of attendees
  1. Feedback score
