### ISSUE TITLE
Open Source EoY Event 

### ISSUE THREAD

**Issue by hpdang** [zalando/zalando.github.io#276]
## Task Headline
Organize an event that features the achievement of Zalando's open source community over the year. 

### Tasks
- [ ] Decide theme and agenda 
- [ ] Book event space
- [ ] Identify external speaker
- [ ] Budget
- [ ] Wowfactor 

### Expected delivery
- The event itself
- Feedback report 

## Stakeholders
- [ ] Event Team 

## How do we measure the task was completed
- No. of attendees
- No. of project presenters
