### ISSUE TITLE
Promotion Framework: Progress Checklist

### ISSUE THREAD

**Issue by hpdang** [zalando/zalando.github.io#289]
This checklist is to capture promotion progress over the period of 3 months. It could be reused in the future. 
- [x] Draft the checklist
- [x] Share with the team for review 
- [x] Share it with the projects

**Comment by hpdang** [comment]
https://docs.google.com/spreadsheets/d/1OnSIdVhfs7OvNR4mwH3HbZPLgIermtlj5SyPuRGg74U/edit#gid=0
