### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#294]
## Task Headline

Evening event at BCS - 4th or 6th floor event space 16:30-20:30
Space for 50 attendees.
 
### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [x] Discuss logistics with COMA
- [x] Get Budget from COMA
- [x] Promote the event
- [x] Introduction and agenda content
- [x] Presenters - reach out to the promo pilots
- [x] Host the event
- [x] Event feedback

## Stakeholders
Who do we need to align with to make this happen? - add the deparment to get in touch with

- [x] Coma
- [x] Presenters

## How do we measure the task was completed
How do we measure impact 

  1. Number of pull requests
  1. Number of attendees
