### ISSUE TITLE
Promo Framework: Consultancy Work Overview Q4

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#295]
## Task Headline

Start the promo framework pilot program, 3 projects are signed up. 

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [x] Collect tweet from projects
- [x] Meet with corp comms to discuss tweets + blog posts + medium and reddit
- [ ] Meetup matching
- [ ] Arrange coordination meeting with pilot teams
- [ ] Review blog posts

## Stakeholders
Who do we need to align with to make this happen? - add the deparment to get in touch with

- [ ] Corp comms
- [ ] Pilot projects
