### ISSUE TITLE
Table of contents for maintainers advocacy training

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#322]
## Advocacy & Stewardship

Based on the following topics, create a detailed outline of the advocacy course.
 
Advocacy - To get usage, feedback, contribution, and recognition. Stewardship - steers the direction of the project, build a sense of ownership and empowerment
Code of Conduct (how do we behave, how to make sure people behave in the community, avoid trolls, disruption, escalation) 
Documentation
Grow community 
Promotion framework (tools) 
Day-to-day operation: issues, PRs, communications, chat, mailing lists, mile stones
Vision/scope of the project, set expectation, roadmap 

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [ ] Topics and detailed content listing
- [ ] Timings for each topic
- [ ] Exercises to support the topics

### Expected delivery

Output: A google drive document with a structured list of content, which is then later converted into a slide deck + exercise descriptions.

## Stakeholders
Who do we need to align with to make this happen? - add the deparment to get in touch with

- [ ] Department name

## How do we measure the task was completed
How do we measure impact 

  1.
  1.
  1.
