### ISSUE TITLE
Table of contents for the maintainer mentorship training

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#323]
## Mentorship  & Coaching

Based on the following topics, create a detailed outline of the advocacy course.
 
Retain people, quality assurance, help contributors to become better at what they are doing. Results better code contribution to the project.  Possibility to get them on board as a Zalando employee. 
Recruitment 
Up for grab 
First timer only 
How to response to criticism and feedback 
Ask for help 
Distribute the work 
Check out Tools

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [ ] Topics and detailed content listing
- [ ] Timings for each topic
- [ ] Exercises to support the topics

### Expected delivery

Output: A google drive document with a structured list of content, which is then later converted into a slide deck + exercise descriptions.
