### ISSUE TITLE
Document on maintainer harassment policy

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#376]
## Create policy document on actions taken in case of harassment

As company support our employees in doing open source, our policy on harassment should be clear and public, this will guide our employees in case of harassment and reassure them that we support their work in open source. 

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [x] Outline actions taken by zalando
- [ ] Background for this
- [ ] Flush out public blog post

### Expected delivery

- Public blog post on this policy
- Harrasment policy and guidelines published on opensource.zalando.net

## Stakeholders
Who do we need to align with to make this happen? - add the department to get in touch with

- [x] p&o
- [ ] Legal
- [ ] Sign-off from VP or head

**Comment by perploug** [comment]
Policy ready for review: https://docs.google.com/document/d/1uSdjbLFE7GYAfoLbakDf5oWyHg5IOiGVxUmBsrlm_8I/edit?usp=sharing

**Comment by hpdang** [comment]
made some comments on the file
