### ISSUE TITLE
Open Source 3rd party services offboarding

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#382]
Zalando Employees have access to external services related to OS development:

- NPM
- Pip
- Maven
- Sonatype

As employees offboard, we must ensure that they are also offboarded from these services. 

### Tasks

- [ ] Investigate if there are org/admin settings on each of the above services
- [ ] Investigate if API access can help us automate this
- [ ] Ensure offboarding is someones responsibility
