### ISSUE TITLE
Github Overhaul

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#47]
- [x] Understand membership structure #42 
- [x] Understand tooling #43 
- [x] New Proposed structure #45 
- [x] Workshop materials #46 
- [x] Write a tech narrative for isssue 66 and 67 #109 
- [x] Inform the guild about the changes #66 
- [ ] Inform tech about the changes #67
