### ISSUE TITLE
Website documents section

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#68]
## Description

Move how-to-oss from github repo into ost website and update its content

### Tasks
This is the concreate tasks to complete before the task is marked as done

- [x] Refactor content #76
  - [x] Update to fit r.o.p 2.0
  - [x] refine the content
- [x] Enable jekyll on the website #78
- [x] design of content #79
- [ ] Archive the how-to-oss repo #72
- [x] Update the review process documentation #71
- [x] Docs template for the website using Jekyll #133

 

### Expected delivery

What is the concrete outcome of this task. 

## Stakeholders
Who do we need to colloborate with to make this happen? - add the deparment to get in touch with

- [ ] Department name

## How do we measure the task was completed
How do we measure impact 

  1.
  1.
  1.
