### ISSUE TITLE
Documentation and training for maintainers

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#69]
## Description

In order to create a high quality experience for contributors to Zalando open source projects. 
We will design a maintainer training program which helps our project maintainers to create and nurture 
welcoming and friendly open source projects. 

### Tasks
This is the concreate tasks to complete before the task is marked as done

 
- [x] Review process for acceptance into the incubator #71 
  - [ ] retire oss review group internal repo
- [x] Define the process for graduating from the incubator #73 
  - [x] Research how apache and fsf incubators define graduation #74 
- [ ] Process for maintainers offboarding from Zalando #77 
- [ ] Maintainer training materials #80

### Expected delivery

Training materials for maintainers, offered through the tech academy to all zalando project maintainers

## Stakeholders
Who do we need to colloborate with to make this happen? - add the deparment to get in touch with

- [ ] OSS Review group
- [ ] OSS Guild
- [ ] OSS Maintainers
