### ISSUE TITLE
Review process for acceptance into the incubator

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#71]
## Description

Review the current documentation on how a project is reviewed and accepted into the incubator
Make documents public so there is full transparency on how a project is accepted and what
rules to follow. 

### Tasks
This is the concreate tasks to complete before the task is marked as done

- [x] Identify and clean up current review docs
- [x] Make public on website
- [ ] Retire internal review group repo

### Expected delivery

Website documentation on the review process for open source projects at zalando
