### ISSUE TITLE
Refactor content from how-to-oss

### ISSUE THREAD

**Issue by princiya** [zalando/zalando.github.io#76]
## Task Headline

Refactor content from here https://github.com/zalando/zalando-howto-open-source to fit inside opensource's website.

### Tasks

 - [x] Update to fit ROP 2.0
 - [x] Rewrite licensing
 - [x] Rewrite release guide
 - [x] Rewrite adopting oss
 - [x] Contributions Upstream

### Expected delivery

The opensource website serving as the single source of truth to serve all content related to opensource && zalando.

## Stakeholders

- [ ] Talk to compliance about the updated changes
 - [ ] Discuss with owners of public rules of play repos

## How do we measure the task was completed
How do we measure impact 

  1.
  1.
  1.
