### ISSUE TITLE
Design for the website documentation

### ISSUE THREAD

**Issue by princiya** [zalando/zalando.github.io#79]
## Task Headline

The refactored documentation from here https://github.com/zalando/zalando-howto-open-source should meet dress-code style.

### Tasks

- [x] Create Jekyll template to meet dress-code style
- [x] Create new document pages based on the above template

### Expected delivery

Create new document pages based on dress-code style via Jekyll and deploy to the opensource website.

## Stakeholders

- [ ] Corporate communications
- [ ] Employer branding
- [ ] Compliance (because of the updated Rules of Play)

## How do we measure the task was completed
How do we measure impact 

  1.
  1.
  1.
