### ISSUE TITLE
Project Maintainer videos

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#99]
## Task Headline

Produce short 5-10 min videos to highlight what zalando open source projects does, how they work with contributors, build community and get an insight into who maintains them.

### Tasks
This is the concrete tasks to complete before the task is marked as done

- [x] Write narrative
- [x] Interview structure document
- [ ] Decide on broadcast approach (us? Team Brotkasten?)

### Expected delivery

A production plan and script for a video format we can start using to produce these videos. 

## Stakeholders
Who do we need to colloborate with to make this happen? - add the deparment to get in touch with

- [ ] Corp comms
- [ ] Employer Branding
- [ ] Maintainers
- [x] open source guild
- [ ] Broadcast Team

## How do we measure the task was completed
How do we measure impact 

  1.
  1.
  1.

**Comment by perploug** [comment]
Ready for review by team, EB, CC
https://docs.google.com/document/d/1G-VcgryfdUMDj0Zl_n9liBb94ct5Uv4rdVkjiYcFSTo/edit#

**Comment by hpdang** [comment]
@perploug please give me access to the doc
